import CloseIcon from "@mui/icons-material/Close";
import React from "react";

const AiModal = ({ isVisible, onClose, description }) => {
  if (!isVisible) return;

  const handleClose = (e) => {
    if (e.target.id === "wrapper") onClose();
  };

  return (
    <div className="text-black ">
      <div
        id="wrapper"
        onClick={handleClose}
        className="fixed inset-0 z-40 bg-black bg-opacity-25 backdrop-blur-sm flex justify-center items-center"
      >
        <div className="flex flex-col w-[600px] max-lg:w-[400px] bg-white p-2 rounded-md shadow-xl">
          <div className="place-self-end  rounded-md cursor-pointer hover:bg-slate-200 p-2">
            <CloseIcon onClick={() => onClose()} />
          </div>
          <div className="py-8 px-4">
            <h1 className="text-3xl text-center mb-4">
              Summay generated by AI
            </h1>
            <div className="divider mb-4"></div>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt
              harum quisquam possimus, nostrum tempora eos itaque minus modi
              quidem non corporis sunt officia nemo dignissimos veritatis soluta
              ab culpa assumenda, reiciendis iusto a accusamus numquam? Incidunt
              molestiae natus eligendi doloribus aliquid harum nihil, esse
              quaerat neque ipsum modi recusandae eos.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AiModal;

// import React, { useRef, useState } from "react";
